version: 2

mkdocs:
  configuration: mkdocs.yml

build:
  os: "ubuntu-lts-latest"
  tools:
    python: "3.12"

  jobs:
    post_create_environment:
      - python -m pip install --upgrade --no-cache-dir mkdocs-material
      - python -m pip install --upgrade --no-cache-dir mkdocs-mermaid2-plugin
      - python -m pip install --upgrade --no-cache-dir mkdocstrings
      - python -m pip install --upgrade --no-cache-dir mkdocstrings-python