version: 2

mkdocs:
  configuration: mkdocs.yml

build:
  os: "ubuntu-lts-latest"
  tools:
    python: "3.11"

  jobs:
    post_create_environment:
      - pip install uv

    post_install:
      - UV_PROJECT_ENVIRONMENT=$READTHEDOCS_VIRTUALENV_PATH uv sync --extra doc --link-mode=copy
