version: 2

mkdocs:
  configuration: mkdocs.yml

build:
  os: "ubuntu-lts-latest"
  tools:
    python: "3.12"

jobs:
  post_create_env:
    - python -m pip install --upgrade pip
    - pip install uv

  post_install:
    - uv sync --extra doc