site_name: new-sus
repo_url: https://github.com/GuttoF/dq-sus
repo_name: dq-sus/src
edit_uri: tree/main/docs

theme:
  name : material
  language: pt-BR

plugins:
  - search
  - mermaid2
  - mkdocstrings
