site_name: PyZDC
repo_url: https://github.com/GuttoF/pyzdc
repo_name: pyzdc
edit_uri: tree/main/docs

theme:
  name: material
  #language: pt-BR
  #logo: assets/logo.png
  #favicon: assets/logo.png
  palette:
    - scheme: default
      primary: teal
      accent: cyan
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
    - scheme: slate
      primary: green
      accent: light green
      toggle:
        icon: material/lightbulb
        name: Switch to light mode

nav:
  - Home: index.md
  - How to use: diagram.md
  - Functions info: functions.md

markdown_extensions: 
  - attr_list

plugins:
  - search
  - mermaid2
  - mkdocstrings:
      handler:
        python:
          paths: [pyzdc]
