site_name: PyZDC
repo_url: https://github.com/GuttoF/pyzdc
repo_name: pyzdc
edit_uri: tree/main/docs

theme:
  name : material
  #language: pt-BR
  #logo: assets/logo.png
  #favicon: assets/logo.png

markdown_extensions: 
  - attr_list

plugins:
  - search
  - mermaid2
  - mkdocstrings
